### ISSUE TITLE
ERROR:    Nack error reading device props: device,93300: unrecognized-service

### ISSUE THREAD

**Issue by Hochram** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#14]
Hi, I have a Salda HVAC system that seems not to be recognized by the add-on, you can see the error in the log down here:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

[34m-----------------------------------------------------------[0m
[34m Add-on: Bepacom BACnet/IP Interface[0m
[34m Bepacom BACnet/IP interface for the Bepacom EcoPanel. Allows BACnet/IP devices to be available to Home Assistant through an API.[0m
[34m-----------------------------------------------------------[0m
[34m Add-on version: 1.3.2[0m
[32m You are running the latest version of this add-on.[0m
[34m System: Home Assistant OS 11.5  (amd64 / qemux86-64)[0m
[34m Home Assistant Core: 2024.2.1[0m
[34m Home Assistant Supervisor: 2024.01.1[0m
[34m-----------------------------------------------------------[0m
[34m Please, share the above information when looking for help[0m
[34m or support in, e.g., GitHub, forums or the Discord chat.[0m
[34m-----------------------------------------------------------[0m
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-interface: starting
[08:27:16] INFO: [32mRunning init-nginx.[0m
[08:27:16] INFO: [32mRunning init-interface.[0m
[08:27:16] INFO: [32mAllowed addresses for NGINX: 127.0.0.1 192.168.1.200 172.30.32.1 172.30.232.1[0m
Using enp0s18 as address: 192.168.1.200/24
[08:27:17] INFO: [32mGenerated ingress configuration successfully![0m
s6-rc: info: service init-nginx successfully started
[BACpypes]
objectName: EcoPanel
address: 192.168.1.200/24
objectIdentifier: 420
maxApduLengthAccepted: 1476
segmentation: segmentedBoth
vendorIdentifier: 15
foreignBBMD: -
foreignTTL: 255
maxSegmentsAccepted: 64
loglevel: WARNING
defaultPriority: 15
updateInterval: 600
s6-rc: info: service init-interface successfully started
s6-rc: info: service interface: starting
s6-rc: info: service interface successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[08:27:17] INFO: [32mRunning interface[0m
s6-rc: info: service legacy-services successfully started
ERROR:    Nack error reading device props: device,93300: unrecognized-service
ERROR:    exception: KeyError('device:93300')
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bacpypes3/app.py", line 899, in indication
    await helperFn(apdu)
  File "/usr/bin/BACnetIOHandler.py", line 162, in do_IAmRequest
    await self.read_object_list(device_identifier=apdu.iAmDeviceIdentifier)
  File "/usr/bin/BACnetIOHandler.py", line 353, in read_object_list
    for obj_id in self.bacnet_device_dict[f"device:{device_identifier[1]}"][
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'device:93300'
ERROR:    An uncaught error occurred: 'IAmRequest' object has no attribute 'apduInvokeID'
NoneType: None
WARNING:  Invalid HTTP request received.
[08:27:47] INFO: [32mRunning NGINX[0m
2024/02/10 08:27:47 [notice] 273#273: using the "epoll" event method
2024/02/10 08:27:47 [notice] 273#273: nginx/1.24.0
2024/02/10 08:27:47 [notice] 273#273: OS: Linux 6.1.74-haos
2024/02/10 08:27:47 [notice] 273#273: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2024/02/10 08:27:47 [notice] 273#273: start worker processes
2024/02/10 08:27:47 [notice] 273#273: start worker process 364
2024/02/10 09:39:48 [info] 364#364: *1 client 127.0.0.1 closed keepalive connection
2024/02/10 09:40:10 [info] 364#364: *3 client 127.0.0.1 closed keepalive connection
ERROR:    Disconnected...

2024/02/10 09:41:47 [info] 364#364: *5 client 172.30.32.2 closed keepalive connection

```

There is an add-on specific for this unit but unfortunately has stopped working after some updates as the add-on was no more serviced.
So after a while I noticed your addon and tried to use the HVAC through Bac net but since now I' wasn't able to.

This are the settings of the unit, basically Bac net address 47808, device ID 93300, address 1

![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/03a8dc87-98b6-4ac6-955a-5ed0d0b5395b)

Integration can't be set up, I imagine because of the error in the log

![Bepacom1](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/4f99df16-06ad-4c18-9f3f-7957658ed329)

Thanks
Regards

**Comment by GravySeal** [comment]
Hello Hochram,

It seems the Salda HVAC system does not support Read Multiple requests. I made an update for the dev version (1.3.3) that should add a way to deal with this issue. Could you try it for me?

Once the add-on is able to read your device, the integration should be able to be added as well. The integration can't do much when the add-on sends empty data.

**Comment by Hochram** [comment]
Hi GravySeal,

thanks for the prompt answer!
I updated the dev version, rebooted all but unfortunately the error stands still:

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

[34m-----------------------------------------------------------[0m
[34m Add-on: Bepacom BACnet/IP Interface Development Version[0m
[34m Bepacom BACnet/IP interface for the Bepacom EcoPanel. Allows BACnet/IP devices to be available to Home Assistant through an API.[0m
[34m-----------------------------------------------------------[0m
[34m Add-on version: 1.3.3[0m
[32m You are running the latest version of this add-on.[0m
[34m System: Home Assistant OS 11.5  (amd64 / qemux86-64)[0m
[34m Home Assistant Core: 2024.2.1[0m
[34m Home Assistant Supervisor: 2024.01.1[0m
[34m-----------------------------------------------------------[0m
[34m Please, share the above information when looking for help[0m
[34m or support in, e.g., GitHub, forums or the Discord chat.[0m
[34m-----------------------------------------------------------[0m
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-interface: starting
[08:29:59] INFO: [32mRunning init-nginx.[0m
[08:29:59] INFO: [32mRunning init-interface.[0m
[08:29:59] INFO: [32mAllowed addresses for NGINX: 127.0.0.1 192.168.1.200 172.30.32.1 172.30.232.1[0m
[08:29:59] INFO: [32mGenerated ingress configuration successfully![0m
s6-rc: info: service init-nginx successfully started
[BACpypes]
objectName: EcoPanel
address: 192.168.1.200/24
objectIdentifier: 420
maxApduLengthAccepted: 1476
segmentation: segmentedBoth
vendorIdentifier: 15
foreignBBMD: -
foreignTTL: 255
maxSegmentsAccepted: 64
loglevel: WARNING
defaultPriority: 15
updateInterval: 60
s6-rc: info: service init-interface successfully started
s6-rc: info: service interface: starting
s6-rc: info: service interface successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[08:30:01] INFO: [32mRunning interface[0m
ERROR:    Nack error reading device props: device,93300: unrecognized-service
ERROR:    exception: KeyError('device:93300')
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bacpypes3/app.py", line 899, in indication
    await helperFn(apdu)
  File "/usr/bin/BACnetIOHandler.py", line 164, in do_IAmRequest
    services_supported = self.bacnet_device_dict[f"device:{device_id}"][
                         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'device:93300'
ERROR:    An uncaught error occurred: 'IAmRequest' object has no attribute 'apduInvokeID'
NoneType: None
WARNING:  Invalid HTTP request received.
[08:30:20] INFO: [32mRunning NGINX[0m
2024/02/11 08:30:20 [notice] 285#285: using the "epoll" event method
2024/02/11 08:30:20 [notice] 285#285: nginx/1.24.0
2024/02/11 08:30:20 [notice] 285#285: OS: Linux 6.1.74-haos
2024/02/11 08:30:20 [notice] 285#285: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2024/02/11 08:30:20 [notice] 285#285: start worker processes
2024/02/11 08:30:20 [notice] 285#285: start worker process 357
ERROR:    Disconnected...

2024/02/11 08:34:59 [info] 357#357: *1 client 172.30.32.2 closed keepalive connection
ERROR:    Disconnected...

`
Regards

**Comment by GravySeal** [comment]
I see where I made the mistake, I just pushed another update. 
After you check for updates in your add-on store you can click rebuild on the add-on page. This should install the latest version for you. Let me know if this works!

**Comment by Hochram** [comment]
Something changed

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

[34m-----------------------------------------------------------[0m
[34m Add-on: Bepacom BACnet/IP Interface Development Version[0m
[34m Bepacom BACnet/IP interface for the Bepacom EcoPanel. Allows BACnet/IP devices to be available to Home Assistant through an API.[0m
[34m-----------------------------------------------------------[0m
[34m Add-on version: 1.3.3[0m
[32m You are running the latest version of this add-on.[0m
[34m System: Home Assistant OS 11.5  (amd64 / qemux86-64)[0m
[34m Home Assistant Core: 2024.2.1[0m
[34m Home Assistant Supervisor: 2024.01.1[0m
[34m-----------------------------------------------------------[0m
[34m Please, share the above information when looking for help[0m
[34m or support in, e.g., GitHub, forums or the Discord chat.[0m
[34m-----------------------------------------------------------[0m
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-interface: starting
[16:27:33] INFO: [32mRunning init-interface.[0m
[16:27:33] INFO: [32mRunning init-nginx.[0m
[16:27:34] INFO: [32mAllowed addresses for NGINX: 127.0.0.1 192.168.1.200 172.30.32.1 172.30.232.1[0m
[16:27:36] INFO: [32mGenerated ingress configuration successfully![0m
s6-rc: info: service init-nginx successfully started
[BACpypes]
objectName: EcoPanel
address: 192.168.1.200/24
objectIdentifier: 420
maxApduLengthAccepted: 1476
segmentation: segmentedBoth
vendorIdentifier: 15
foreignBBMD: -
foreignTTL: 255
maxSegmentsAccepted: 64
loglevel: WARNING
defaultPriority: 15
updateInterval: 60
s6-rc: info: service init-interface successfully started
s6-rc: info: service interface: starting
s6-rc: info: service interface successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[16:27:42] INFO: [32mRunning interface[0m
ERROR:    Nack error reading device props: device,93300: unrecognized-service
ERROR:    Nack error reading device props one by one: device,93300: property: unknown-property
ERROR:    Nack error reading device props one by one: device,93300: property: unknown-property
ERROR:    Nack error: device,93300: property: unknown-property
WARNING:  Invalid HTTP request received.
[16:27:59] INFO: [32mRunning NGINX[0m
2024/02/11 16:27:59 [notice] 284#284: using the "epoll" event method
2024/02/11 16:27:59 [notice] 284#284: nginx/1.24.0
2024/02/11 16:27:59 [notice] 284#284: OS: Linux 6.1.74-haos
2024/02/11 16:27:59 [notice] 284#284: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2024/02/11 16:27:59 [notice] 284#284: start worker processes
2024/02/11 16:27:59 [notice] 284#284: start worker process 351
ERROR:    Disconnected...

2024/02/11 16:29:13 [info] 351#351: *1 client 172.30.32.2 closed keepalive connection
ERROR:    Disconnected...

ERROR:    Nack error reading device props: device,93300: unrecognized-service
ERROR:    Nack error reading device props one by one: device,93300: property: unknown-property
ERROR:    Nack error reading device props one by one: device,93300: property: unknown-property
ERROR:    Nack error: device,93300: property: unknown-property
ERROR:    Disconnected...

2024/02/11 16:44:57 [info] 351#351: *17 client 172.30.32.2 closed keepalive connection
ERROR:    Disconnected...

2024/02/11 16:45:45 [info] 351#351: *21 client 172.30.32.2 closed keepalive connection

```

I can see the device in the add-on page with properties, I can add the integration ( but only using local host (127.0.01) and not using Home Assistant IP) but no devices/entities are created.

![Bepacom](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/dfa9d523-0e73-4806-b50d-855f651577d5)
![Bepacom2](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/178b41f2-95b1-4e7b-af20-856aa950f10e)
![Bepacom3](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/65b99247-9ee9-4ee5-af23-361b871e5ea7)

Thanks

**Comment by GravySeal** [comment]
Would you mind trying again? I added some better handling for individual properties.
Hopefully you should be able to see all the data available then.

**Comment by Hochram** [comment]
It just doesn't want to collaborate it seems

```

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Bepacom BACnet/IP Interface Development Version
 Bepacom BACnet/IP interface for the Bepacom EcoPanel. Allows BACnet/IP devices to be available to Home Assistant through an API.
-----------------------------------------------------------
 Add-on version: 1.3.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (amd64 / qemux86-64)
 Home Assistant Core: 2024.2.1
 Home Assistant Supervisor: 2024.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-interface: starting
[19:22:58] INFO: Running init-nginx.
[19:22:58] INFO: Running init-interface.
[19:22:58] INFO: Allowed addresses for NGINX: 127.0.0.1 192.168.1.200 172.30.32.1 172.30.232.1
[19:23:02] INFO: Generated ingress configuration successfully!
s6-rc: info: service init-nginx successfully started
[BACpypes]
objectName: EcoPanel
address: 192.168.1.200/24
objectIdentifier: 420
maxApduLengthAccepted: 1476
segmentation: segmentedBoth
vendorIdentifier: 15
foreignBBMD: -
foreignTTL: 255
maxSegmentsAccepted: 64
loglevel: WARNING
defaultPriority: 15
updateInterval: 60
s6-rc: info: service init-interface successfully started
s6-rc: info: service interface: starting
s6-rc: info: service interface successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[19:23:11] INFO: Running interface
ERROR:    Nack error reading device props: device,93300: unrecognized-service
ERROR:    Nack error reading device props one by one: device,93300: max-segments-accepted property: unknown-property
ERROR:    Nack error reading device props one by one: device,93300: serial-number property: unknown-property



ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
```

I don't know what exactly in the lines missing as it starts to spam in loop the last line and it's difficult to get on the log.
Keep up the god job :)

**Comment by GravySeal** [comment]
The error lines aren't necessarily an issue, it's just trying to read BACnet properties that don't exist on your device. If you look in the web UI, is there more data?

**Comment by Hochram** [comment]
Sorry, I missed the important bit.
Unfortunately, still no devices/entities

![Bepacom](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/245dd057-66f5-455c-b57a-5c470aecf90d)

**Comment by GravySeal** [comment]
Does the addon Web UI show any objects and properties?

**Comment by Hochram** [comment]
![bepacom](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/3d64a403-1e11-4bf7-bc38-46b8972b0dc2)
![bepacom2](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/5cd32d05-1656-41a8-83c4-45ecb55d8885)

**Comment by GravySeal** [comment]
Any objects below the device object?

**Comment by Hochram** [comment]
Hope you mean here

![bepacom](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/adbd9349-2a62-4ded-9330-91f5ef76cefc)
![bepacom2](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/5132062e-0d55-43f9-a4be-abb1f2435622)

Can't see anything else

**Comment by GravySeal** [comment]
Could you perhaps check for updates, rebuild and post the logs again? I made the logging slightly more detailed. Hopefully I can find the issue then.

**Comment by Hochram** [comment]
Here are the new logs:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Bepacom BACnet/IP Interface Development Version
 Bepacom BACnet/IP interface for the Bepacom EcoPanel. Allows BACnet/IP devices to be available to Home Assistant through an API.
-----------------------------------------------------------
 Add-on version: 1.3.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (amd64 / qemux86-64)
 Home Assistant Core: 2024.2.1
 Home Assistant Supervisor: 2024.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-interface: starting
[20:48:59] INFO: Running init-nginx.
[20:48:59] INFO: Running init-interface.
[20:48:59] INFO: Allowed addresses for NGINX: 127.0.0.1 192.168.1.200 172.30.32.1 172.30.232.1
[20:49:02] INFO: Generated ingress configuration successfully!
s6-rc: info: service init-nginx successfully started
[BACpypes]
objectName: EcoPanel
address: 192.168.1.200/24
objectIdentifier: 420
maxApduLengthAccepted: 1476
segmentation: segmentedBoth
vendorIdentifier: 15
foreignBBMD: -
foreignTTL: 255
maxSegmentsAccepted: 64
loglevel: WARNING
defaultPriority: 15
updateInterval: 60
s6-rc: info: service init-interface successfully started
s6-rc: info: service interface: starting
s6-rc: info: service interface successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[20:49:06] INFO: Running interface
ERROR:    Nack error reading device props: device,93300: unrecognized-service
ERROR:    Nack error reading device props one by one: device,93300: max-segments-accepted property: unknown-property
ERROR:    Nack error reading device props one by one: device,93300: serial-number property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
ERROR:    Nack error reading object list one by one: device,93300: property: unknown-property
```

Noticed this when checking supervisor after rebuild, just fyi

![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/fd817fe3-cdb4-4912-9098-da0aeeb0b454)

**Comment by GravySeal** [comment]
Would you mind checking for updates and rebuilding again? Seems the update didn't come through this attempt.

> Noticed this when checking supervisor after rebuild, just fyi

This seems to indicate there might be something wrong in the configuration. If you want to go back to the default settings you can also just remove and reinstall the add-on.

**Comment by GravySeal** [comment]
To me it looks like there are no properties at all in the BACnet objects. Do you know YABE? What results do you get if you try to read it with YABE?

https://sourceforge.net/projects/yetanotherbacnetexplorer/

**Comment by Hochram** [comment]
Hi,

it seems Yabe is able to read all the properties as are also reported on the Salda interface

![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/949fb4e3-1465-476a-bc57-97fd8f7321e2)
![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/d6d64510-1948-4efc-ba6e-8c94ea48da1f)

For example:

![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/1a82d7b9-0bbe-4c96-a080-854c5df6f2c7)

Anyway, thanks for the YABE tip, didn't know it or maybe tried with no luck years ago..

**Comment by Bepacom-Raalte** [comment]
Hello,

I think I found the issue. Could you check for updates and rebuild the add-on?

**Comment by Hochram** [comment]
Bingo!!

![immagine](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/35610308/366052dd-ae9b-4bfd-b8d0-4577cda9d806)

Great work, thanks!
If you need to test something, count on me ;)

**Comment by Bepacom-Raalte** [comment]
Wonderful, great to see! If there are any other problems, please feel free to create a new issue here on GitHub!
