### ISSUE TITLE
Error setting up entry BACnet Interface for bacnet_interface

### ISSUE THREAD

**Issue by ictforum-nl** [Bepacom-Raalte/Bepacom-BACnet-IP-Integration#15]
Hoi, na de update naar de laatste versie krijg ik een foutmelding in de integratie:
ik krijg deze zowel met de standaard als de dev. versie van de add-on

Logger: homeassistant.config_entries
Source: config_entries.py:444
First occurred: 13:02:22 (3 occurrences)
Last logged: 13:12:55

Error setting up entry BACnet Interface for bacnet_interface
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bacnet_interface/__init__.py", line 43, in async_setup_entry
    coordinator = EcoPanelDataUpdateCoordinator(hass, entry=entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bacnet_interface/coordinator.py", line 33, in __init__
    port=entry.data[CONF_PORT],
         ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'port'

**Comment by GravySeal** [comment]
Wanneer je de integration configureert, heb je nu meerdere opties om in te vullen. Wanneer je de configuratie van de integratie update met poort 8099 zal deze weer moeten werken.

**Comment by ictforum-nl** [comment]
hoi, poort 8099 leek al goed te staan, maar ik ben inmiddels wat verder, ik krijg geen foutmelding bij het starten van de addon en integratie, maar ik krijg ook geen informatie in de entities.
ik heb hieronder de log van de addon, (heb onze url aangepast):

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: Bepacom BACnet/IP Interface
 Bepacom BACnet/IP interface for the Bepacom EcoPanel. Allows BACnet/IP devices to be available to Home Assistant through an API.
-----------------------------------------------------------
 Add-on version: 1.3.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.5  (amd64 / qemux86-64)
 Home Assistant Core: 2024.2.1
 Home Assistant Supervisor: 2024.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-interface: starting
[09:23:59] INFO: Running init-nginx.
[09:23:59] INFO: Running init-interface.
[09:23:59] INFO: Allowed addresses for NGINX: 127.0.0.1 172.25.41.252 172.20.140.176 172.20.170.9 192.168.40.250 172.30.32.1 172.30.232.1
[09:23:59] INFO: Generated ingress configuration successfully!
s6-rc: info: service init-nginx successfully started
[BACpypes]
objectName: Honeywell
address: 192.168.40.250/24
objectIdentifier: 420
maxApduLengthAccepted: 1476
segmentation: segmentedBoth
vendorIdentifier: 15
foreignBBMD: 192.168.40.250
foreignTTL: 255
maxSegmentsAccepted: 64
loglevel: WARNING
defaultPriority: 15
updateInterval: 60
s6-rc: info: service init-interface successfully started
s6-rc: info: service interface: starting
s6-rc: info: service interface successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
[09:23:59] INFO: Running interface
s6-rc: info: service legacy-services successfully started
WARNING:  Invalid HTTP request received.
[09:24:05] INFO: Running NGINX
2024/02/15 09:24:05 [notice] 287#287: using the "epoll" event method
2024/02/15 09:24:05 [notice] 287#287: nginx/1.24.0
2024/02/15 09:24:05 [notice] 287#287: OS: Linux 6.1.74-haos
2024/02/15 09:24:05 [notice] 287#287: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2024/02/15 09:24:05 [notice] 287#287: start worker processes
2024/02/15 09:24:05 [notice] 287#287: start worker process 337
ERROR:    Disconnected...

2024/02/15 09:32:41 [warn] 337#337: *10 an upstream response is buffered to a temporary file /var/lib/nginx/tmp/proxy/1/00/0000000001 while reading upstream, client: 172.30.32.2, server: , request: "GET /webapp HTTP/1.1", upstream: "http://127.0.0.1:7813/webapp", host: "biebhulp.forum.nl:8123", referrer: "https://biebhulp.forum.nl:8123/97683af0_bacnetinterface"
ERROR:    Disconnected...

**Comment by ictforum-nl** [comment]
de entities die ik had geconfigureerd geven allemaal "Niet Beschikbaar"

**Comment by Bepacom-Raalte** [comment]
Heb je toevallig de optie aangevinkt om de beschrijving te gebruiken als entity naam?
Dit zou niet uit moeten maken als je de integration als eerste hebt toegevoegd met object namen.
Als je de integration hebt verwijderd en dan toevoegt met deze optie, zullen de oude namen niet meer werken.

**Comment by ictforum-nl** [comment]
de integratie lijkt geen entities uit de addon te krijgen, ook als ik de integratie opnieuw installeer komen er geen objecten binnen..

**Comment by Bepacom-Raalte** [comment]
Als je in de web UI van de add-on kijkt, zitten er objecten in?

**Comment by ictforum-nl** [comment]
Ja, daar zie ik wel van alles staan.

**Comment by Bepacom-Raalte** [comment]
Zou je de laatste foutmeldingen kunnen delen van de integration?

**Comment by Bepacom-Raalte** [comment]
Is het toevallig nog gelukt?

**Comment by ictforum-nl** [comment]
Hoi, excuus was er een weekje tussenuit. het is nog niet gelukt.
ook niet na de laatste update die klaarstond voor de addon.

ik zie nu deze foutmelding:

Logger: homeassistant.components.select
Source: helpers/entity_platform.py:344
Integration: Selecteer (documentation, issues)
First occurred: 09:40:37 (2 occurrences)
Last logged: 09:43:12

Error while setting up bacnet_interface platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bacnet_interface/select.py", line 34, in async_setup_entry
    coordinator.data.devices[deviceid].objects[objectid].objectIdentifier[0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by ictforum-nl** [comment]
en deze in de Addon:
Bepacom BACnet/IP Interface Development Version
WARNING:    Replacing with 0: device,60, analog-output,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,60, analog-output,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,53, analog-output,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,53, analog-output,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,62, analog-output,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,62, analog-output,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,54, analog-output,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,54, analog-output,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,58, analog-output,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,58, analog-output,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,55, analog-output,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,55, analog-output,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,51, analog-output,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,51, analog-output,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,56, analog-output,1, min-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,56, analog-output,1, max-pres-value... Inf value: inf
WARNING:    Replacing with 0: device,112, analog-output,0, min-pres-value... Inf value: -inf
WARNING:    Replacing with 0: device,112, analog-output,0, max-pres-value... Inf value: inf
WARNING:    Abort PDU error while reading device properties: device,570: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,544: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,578: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,540: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,574: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,525: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,569: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,532: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,567: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,526: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,579: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,545: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,571: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,546: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,568: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,542: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,580: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,543: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,577: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,566: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,563: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,573: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,564: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,575: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,548: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,508: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,565: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,531: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,513: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,572: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,538: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,562: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,533: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,576: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,539: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,547: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,561: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,516: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,541: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,515: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,534: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,507: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,537: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,505: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,536: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,514: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,535: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,512: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,504: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,503: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,506: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,518: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,700: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,522: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,523: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,501: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,519: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,520: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,509: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,524: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,517: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,521: segmentation-not-supported
WARNING:    Abort PDU error while reading device properties: device,510: segmentation-not-supported
[09:56:01] INFO: Running NGINX
WARNING:  Invalid HTTP request received.
2024/02/26 09:56:01 [notice] 287#287: using the "epoll" event method
2024/02/26 09:56:01 [notice] 287#287: nginx/1.24.0
2024/02/26 09:56:01 [notice] 287#287: OS: Linux 6.1.74-haos
2024/02/26 09:56:01 [notice] 287#287: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
2024/02/26 09:56:01 [notice] 287#287: start worker processes
2024/02/26 09:56:01 [notice] 287#287: start worker process 338
WARNING:    Abort PDU error while reading device properties: device,5: no-response
ERROR:    exception: KeyError('device:5')
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bacpypes3/app.py", line 899, in indication
    await helperFn(apdu)
  File "/usr/bin/BACnetIOHandler.py", line 159, in do_IAmRequest
    services_supported = self.bacnet_device_dict[f"device:{device_id}"][
                         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'device:5'
ERROR:    An uncaught error occurred: 'IAmRequest' object has no attribute 'apduInvokeID'
NoneType: None

**Comment by ictforum-nl** [comment]
WARNING:    Replacing with 0: device,51, analog-output,1, max-pres-value... Inf value: inf
ERROR:    invalid state transition from COMPLETED to AWAIT_CONFIRMATION
NoneType: None
ERROR:    An uncaught error occurred: invalid state transition from COMPLETED to AWAIT_CONFIRMATION
NoneType: None
ERROR:    Exception reading device props one by one:vendor-identifier unsigned application tag expected
WARNING:    Abort PDU error while reading device properties: device,5: no-response
ERROR:    exception: KeyError('device:5')
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/bacpypes3/app.py", line 899, in indication
    await helperFn(apdu)
  File "/usr/bin/BACnetIOHandler.py", line 159, in do_IAmRequest
    services_supported = self.bacnet_device_dict[f"device:{device_id}"][
                         ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'device:5'
ERROR:    An uncaught error occurred: 'IAmRequest' object has no attribute 'apduInvokeID'
NoneType: None
WARNING:    Abort PDU error while reading device properties: device,570: segmentation-not-supporte

**Comment by Bepacom-Raalte** [comment]
Zou je de dev versie van de add-on eens kunnen updaten? Lijkt erop dat device 5 niet wilde reageren op de read request.

**Comment by ictforum-nl** [comment]
Dat zou toch een kwestie van deinstalleren en opnieuw installeren moeten zijn?
ik zie in de addon wel de meterstanden die ik zoek, maar die komen niet in de integratie. (er zit niets in de integratie)
[home-assistant_2024-02-27T13-08-45.380Z.log](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14419924/home-assistant_2024-02-27T13-08-45.380Z.log)

**Comment by Bepacom-Raalte** [comment]
Dat is een kwestie van eerst even checken voor updates in de add-on store en dan opnieuw installeren inderdaad.
Voor de integration, heb je toevallig de laatste versie vanuit HACS geinstalleerd?

**Comment by ictforum-nl** [comment]
Ja, de laatste uit Hacs idd.

**Comment by Bepacom-Raalte** [comment]
Als je de dev versie van de add-on opnieuw hebt geinstalleerd en je Home Assistant opnieuw hebt geladen, welke melding krijg je dan?

**Comment by ictforum-nl** [comment]
Hoi, ik heb Home assistant opnieuw gestart, heb de laatste Dev versie en laatste integratie dan krijg ik deze meldingen in het logboek:
[home-assistant_2024-02-28T09-17-33.210Z.log](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14431449/home-assistant_2024-02-28T09-17-33.210Z.log)

**Comment by Bepacom-Raalte** [comment]
En wat geeft de add-on weer in de logs wanneer je deze op INFO logging niveau zet?

**Comment by ictforum-nl** [comment]
dan haal ik dit eruit

[97683af0_bacnetinterface_dev_2024-02-28T10-32-52.169Z.log](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14432571/97683af0_bacnetinterface_dev_2024-02-28T10-32-52.169Z.log)
[97683af0_bacnetinterface_dev_2024-02-28T10-32-43.833Z.log](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14432572/97683af0_bacnetinterface_dev_2024-02-28T10-32-43.833Z.log)

**Comment by Bepacom-Raalte** [comment]
In de add-on web UI, zou je het volgende kunnen doen?

1. Ga naar API Docs,

![afbeelding](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/126168314/72d6f5df-63c3-45e7-a5c7-56d281bea5a2)

2. Ga naar /apviv1/json,

![afbeelding](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/126168314/eb8d27be-f43b-4ec8-9758-67529101772c)

3. Klik op Try it out en dan op Execute.

![afbeelding](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/126168314/134d5304-98fc-4ac2-8640-3311ee80099c)

4. Klik op download en deel het .json bestand met mij.

**Comment by Bepacom-Raalte** [comment]
Zou je mij de logs kunnen sturen wanneer je dit probeert?
Zou je ook eens met Yabe kunnen bevestigen dat je apparaat 5 kan bereiken?

**Comment by ictforum-nl** [comment]
in Yabe zie ik deze devices:
![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/107480811/1f34face-2da3-4bde-b047-f4a1bc1b10fe)

ik hoop dat je iets in deze logs kunt zien:

[97683af0_bacnetinterface_dev_2024-03-04T11-00-06.708Z.log](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14480442/97683af0_bacnetinterface_dev_2024-03-04T11-00-06.708Z.log)
[97683af0_bacnetinterface_dev_2024-03-04T11-00-21.940Z.log](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14480443/97683af0_bacnetinterface_dev_2024-03-04T11-00-21.940Z.log)
[97683af0_bacnetinterface_dev_2024-03-04T10-59-41.620Z.log](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14480444/97683af0_bacnetinterface_dev_2024-03-04T10-59-41.620Z.log)

**Comment by Bepacom-Raalte** [comment]
Zit device 5 toevallig ergens onder deze apparaten?
Ik heb vandaag ook een kleine update gepusht onder dezelfde versie. 
Kun je eens kijken of die versie verschil maakt?

**Comment by ictforum-nl** [comment]
hoi , nadat ik de add-on heb verwijderd en opnieuw heb geinstalleeerd heb ik ook segmentation op "no-segmentation" gezet.
nu krijg ik wel de json:
[response_1709623752062.json](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14491860/response_1709623752062.json)

de integratie lijkt nog steeds niets te vinden..

**Comment by Bepacom-Raalte** [comment]
Ik zie een aantal aparte dingen in de json, namelijk dat vanaf de device 5** reeks de device properties niet opgehaald worden.
Is dit omdat nog niet alles is opgehaald of omdat er problemen over zijn verschenen in de logs?

**Comment by ictforum-nl** [comment]
in de systeem logs komt deze foutmelding:
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:344
Integration: Sensor (documentation, issues)
First occurred: 08:38:22 (1 occurrences)
Last logged: 08:38:22

Error while setting up bacnet_interface platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 344, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bacnet_interface/sensor.py", line 38, in async_setup_entry
    coordinator.data.devices[deviceid].objects[objectid].objectIdentifier[0]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

en die komt dan voor: sensor, binary sensor, number , switch en voor select.

[97683af0_bacnetinterface_dev_2024-03-05T09-01-24.872Z.log](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14492836/97683af0_bacnetinterface_dev_2024-03-05T09-01-24.872Z.log)

**Comment by Bepacom-Raalte** [comment]
Ik heb de dev add-on geüpdatet om logs te kunnen exporteren via de web UI. Zou je kunnen checken voor updates en de add-on herbouwen of herinstalleren?
Wanneer dit gebeurd is, moet je in de add-on configuratie de "Export Logs" optie aanvinken en dan via de web UI de logs downloaden.
Ik hoop dat die logs wat helderheid brengen in wat er gebeurd.

**Comment by ictforum-nl** [comment]
hmm, vooralsnog krijg ik een pagina met 404 als ik download logs klik.. maar misschien moet hij iets langer draaien..

**Comment by Bepacom-Raalte** [comment]
Als je een 404 error krijgt, betekent het dat je de configuratie nog niet hebt aangevinkt. Wanneer dit gedaan is, krijg je een log bestandje vanuit je browser.

**Comment by ictforum-nl** [comment]
ah, klopt, bij deze:
[bacnet_addon_logs.txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14615729/bacnet_addon_logs.txt)

**Comment by ictforum-nl** [comment]
[bacnet_addon_logs (1).txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14615749/bacnet_addon_logs.1.txt)

**Comment by Bepacom-Raalte** [comment]
Top, bedankt voor de logs. 
Ik denk dat het misschien voor sommige apparaten te snel gaat. Ik heb in de add-on nu zo gemaakt dat ieder apparaat 1 voor 1 wordt uitgelezen. Hopelijk lost dit in ieder geval problemen op van apparaten die niet reageren.
Zou je de dev versie naar 1.4.0 kunnen updaten?

**Comment by ictforum-nl** [comment]
Hoi, ik heb geupdate, maar nog steeds laat de integratie niets zien. 

[bacnet_addon_logs (3).txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14634820/bacnet_addon_logs.3.txt)
[home-assistant_bacnet_interface_2024-03-18T10-27-25.705Z.log](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14634824/home-assistant_bacnet_interface_2024-03-18T10-27-25.705Z.log)

**Comment by Bepacom-Raalte** [comment]
Ik heb de integration op HACS geupdated naar v0.1.6b. Hopelijk worden nu alle entities in ieder geval aangemaakt.

**Comment by ictforum-nl** [comment]
Hoi, ik heb de integratie opnieuw geinstalleerd, en er gebeurt nu weer iets, ik krijg weer entities in de integratie, maar (nog) niet alles. ik heb de json niet handmatig aangepast, moet dat nog?
![Sensoren HA](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/107480811/92f84d11-1107-4c02-afb5-cc7f09fd0aec)
als ik in de addon zoek op bijv. rk6 dan vind ik die ook niet..

**Comment by ictforum-nl** [comment]
[bacnet_addon_logs (4).txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14663812/bacnet_addon_logs.4.txt)
Als ik hier zoek op device,109 dan ziek ik dit:
INFO->BACnetIOHandler.py->do_IAmRequest:    I Am from device,109
DEBUG->BACnetIOHandler.py->do_IAmRequest:    Device device,109 already in cache!
ook voor device,108 hetzelfde
en die laat hij dan niet zien
en

**Comment by ictforum-nl** [comment]
dan duurt het wel heeeeel lang voordat rk6 verschijnt.. 
rk6_c109 zou ik als device,109 terug moeten vinden volgens mij.
dat zie ik bijv. bij rk4_c105 wel terug met waardes.

**Comment by Bepacom-Raalte** [comment]
Ik zal hier even naar kijken, Ik denk dat device 5 roet in het eten gooit, want deze stuurt wel een I Am request, maar reageert verder niet op read requests.
Er moet sowieso nog het een en ander in de add-on veranderd worden, dus daar valt dit ook onder.

**Comment by ictforum-nl** [comment]
ok, dank in elk geval dat je zo actief bezig bent...

**Comment by Bepacom-Raalte** [comment]
Geen probleem! Ik heb graag dat het werkt. Zou je dev versie 1.4.0 kunnen updaten? Als een apparaat (zoals device 5) niet reageert, zou deze nu overgeslagen moeten worden. Ik ben benieuwd of het zo beter werkt.

**Comment by ictforum-nl** [comment]
Hmm, nu is er weer wat weggevallen. de integratie geeft nu "instellen mislukt"
[bacnet_addon_logs (6).txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14666158/bacnet_addon_logs.6.txt)

**Comment by Bepacom-Raalte** [comment]
Dit lijkt nog niet de juiste versie, Zou je kunnen checken voor updates in de add-on store en dan herbouwen?

**Comment by ictforum-nl** [comment]
Is er een manier dat ik kan zien of ik de juiste versie heb? 
[bacnet_addon_logs (8).txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14666667/bacnet_addon_logs.8.txt)

**Comment by Bepacom-Raalte** [comment]
Dit is de juiste versie, een beetje lastig voor jou om te zien. De add-on gedroeg zich als verwacht nu. Ik heb nu het volgende foutje aangepast. Als je nog 1 keer hetzelfde zou willen doen... Hopelijk komt dan uiteindelijk alles in de add-on te staan.

**Comment by ictforum-nl** [comment]
Yes! dat zijn ze weer allemaal!
top!

**Comment by Bepacom-Raalte** [comment]
Top, goed om te horen!
Kun je de logs en het json bestandje delen? Dan kan ik zien of er nog iets verkeerd gaat.

**Comment by ictforum-nl** [comment]
en nu laad de integration niet meer..

**Comment by ictforum-nl** [comment]
en nu weer wel..

**Comment by Bepacom-Raalte** [comment]
Laat maar weten als het probleem blijft. Is het de laatste versie vanuit HACS?

**Comment by ictforum-nl** [comment]
ik heb zojuist de  1.4.0b3 geïnstalleerd, zal even kijken hoe dat gaat

**Comment by ictforum-nl** [comment]
welke versie van de integratie moet ik gebruiken?
die uit de main? of 1 van de beta versies?
van de addon krijg ik nu 1.4.0b4

**Comment by Bepacom-Raalte** [comment]
Probeer de beta versie v0.1.6b6 van de integration maar. Dit is de meest recente en zou ook een aantal probleempjes op moeten lossen.

**Comment by ictforum-nl** [comment]
als ik de main versie gebruik wil hij niet meer installeren "unknown error occurred"

[bacnet_addon_logs (12).txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14744525/bacnet_addon_logs.12.txt)

**Comment by Bepacom-Raalte** [comment]
Waar komt "unknown error occurred" vandaan? HACS heeft het liefste een versie die geselecteerd wordt. Daarom kun je het beste integration versie v0.1.6b6 proberen.

**Comment by ictforum-nl** [comment]
ok, ik heb nu v0.1.6b6
![unknown error](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/107480811/c920106e-2570-459c-
a9bb-6a9d1ae6ab98)
bij het installeren van de integratie

**Comment by ictforum-nl** [comment]
[Logger aiohttp.server.txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14755447/Logger.aiohttp.server.txt)
dit staat in de system logs

**Comment by Bepacom-Raalte** [comment]
Zou je de add-on logs en een json bestandje kunnen delen?

**Comment by ictforum-nl** [comment]
[bacnet_addon_logs (13).txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14757016/bacnet_addon_logs.13.txt)
[response_1711449567239.json](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14757017/response_1711449567239.json)

zeker, de json failde weer, daarvoor moest ik in de configuratie van de addon "nosegmentation" weer kiezen en herstarten.

**Comment by Bepacom-Raalte** [comment]
Kun je eens de logs delen wanneer je de json met segmentation probeert te genereren? Ik ben benieuwd naar die fout.

**Comment by ictforum-nl** [comment]
Zeker:
[bacnet_addon_logs.txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14760953/bacnet_addon_logs.txt)

**Comment by Bepacom-Raalte** [comment]
Het probleem is niet in deze log in beeld gebracht, dus zou je versie 1.4.0b5 kunnen installeren?
Dan vlak na het opstarten, probeer eens een json te genereren (met segmentation) en daarna meteen een log downloaden. Daar zou dan de fout in moeten staan.

**Comment by ictforum-nl** [comment]
[bacnet_addon_logs (1).txt](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/files/14764353/bacnet_addon_logs.1.txt)
Nu lijkt hij het wel te doen

**Comment by ictforum-nl** [comment]
Hmm, langzaam komen er in de integration steeds meer apparaten bij, al heb ik sinds gisteravond nog niet alles weer online. de Waardes lijken ook bijgewerkt te worden.

**Comment by Bepacom-Raalte** [comment]
De laatste integration versie ververst zichzelf wanneer hij nieuwe apparaten en objecten krijgt via de add-on, mogelijk was de add-on dan nog niet klaar met laden.

**Comment by ictforum-nl** [comment]
Ja, ik lijk alles te missen van device 109:

![image](https://github.com/Bepacom-Raalte/Bepacom-BACnet-IP-Integration/assets/107480811/6c1f6556-80f0-446b-9393-01c9021a4241)

**Comment by ictforum-nl** [comment]
ik zie wel een update klaarstaan:
Installed version 1.4.0b5
Latest version 1.4.0
moet ik die nog installeren?

**Comment by Bepacom-Raalte** [comment]
Top, goed om te horen. Versie 1.4.0 is alleen rechtgetrokken naar de stabiele versie, dus daarin is niet veel veranderd.
